# Site settings
title: Ben Tanen
email: ben.tanen@gmail.com
description: "This is the personal website of Ben Tanen. It includes posts written by him and links to other content from Ben."
baseurl: ""
url: "http://ben-tanen.github.io"
twitter_username: ben_tanen
github_username:  ben-tanen

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
permalink: /projects/:year/:month/:day/:title.html

# Collections
collections:
  generative-sketches:
    sort_by: date
    output: true
    permalink: /projects/generative-sketchbook/:year/:month/:day/:title.html

